### ISSUE TITLE
Meta Programming

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/Gears#1]
Basic meta programming module that contains the following:
- [x] Actual type traits
- [x] Meta functions
- [x] Aliases to common type traits.
- [x] Indices
- [x] Expand variadic templates

**Comment by Rapptz** [comment]
Actual type traits has been moved into the more versatile Concepts module, see Issue #9
