### ISSUE TITLE
The Great Rename of Meta

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/Gears#23]
This is a breaking change.

Since C++14 got accepted, the (unfortunate) naming of template aliases has been standardised and it's best to be consistent with the standard. I propose the following renames:
- [x] `Type<T>` -> `eval<T>`
- [x] All template aliases will go from `PascalCase` to `snake_case_t`
- [x] `And` -> `all`
- [x] `Or` -> `any`
- [x] `Not` -> `negate`
- [x] `If` -> `if_`
- [x] `LazyIf` -> `lazy_if`
- [x] `Const` -> `constant`
- [x] `Integer` -> `integer`
- [x] Metafunctions etc turned from `PascalCase` to `snake_case`.
- [x] Make `indices` follow the C++14 standard naming.

PascalCase should be reserved for concepts only.
